# -*- coding: utf-8 -*-
"""CRYPTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vH4IgEY-JsmGzoFJ8rZIbJepgPq5_2AM

**UPLOADING THE DATASET**
"""

from google.colab import files
uploaded = files.upload()

"""**DATA PROCESSING**"""

import json
from datetime import datetime

input_file = "History (1).json"
output_file = "titles_with_timestamp.txt"

def convert_time_usec_to_readable(time_usec):
    time_seconds = time_usec / 1000000
    dt_object = datetime.fromtimestamp(time_seconds)
    return dt_object.strftime("%Y-%m-%d %H:%M:%S")

# Load JSON
with open(input_file, "r") as file:
    data = json.load(file)

# Extract title + timestamp
entries = [
    (entry["title"], entry["time_usec"])
    for entry in data.get("Browser History", [])
    if entry["title"].strip() != ""
]

# ✅ Remove duplicates (important)
unique_entries = list(set(entries))

# Write to file
with open(output_file, "w") as file:
    for title, time_usec in unique_entries:
        readable_timestamp = convert_time_usec_to_readable(time_usec)
        file.write(f"{readable_timestamp}: {title}\n")

print(f"Extracted {len(unique_entries)} cleaned entries")

"""**FORMATTING THE DATA**"""

# Read cleaned data
with open("titles_with_timestamp.txt", "r") as file:
    lines = file.readlines()

# 🔥 Define broader suspicious keywords (expanded list)
keywords = [
    "hack", "hacker", "attack", "exploit", "malware", "virus",
    "crypto", "bitcoin", "torrent", "piracy", "crack",
    "dark web", "leak", "breach", "password", "phishing",
    "anonymous", "ddos", "spoof"
]

# 🔹 Extract suspicious entries
suspicious = [line for line in lines if any(k in line.lower() for k in keywords)]

# 🔹 Fallback if no suspicious entries found
if len(suspicious) == 0:
    print("⚠️ No suspicious activity found. Using general browsing data instead.\n")
    selected = lines[:1000]
else:
    print(f"✅ Suspicious entries found: {len(suspicious)}\n")
    selected = suspicious[:1000]  # limit if too many

# 🔹 Format for LLM
formatted_data = "User Browser Activity Analysis:\n\n"

for line in selected:
    formatted_data += f"- {line.strip()}\n"

# Preview
print(formatted_data[:1000])

with open("titles_with_timestamp.txt", "r") as file:
    final_lines = file.readlines()

"""**TOP INTERESTS**"""

categories = {
    "youtube": "entertainment",
    "netflix": "entertainment",
    "amazon": "shopping",
    "flipkart": "shopping",
    "linkedin": "professional",
    "github": "technology",
    "stack overflow": "technology",
    "reddit": "social",
    "instagram": "social"
}

from collections import Counter

category_count = Counter()

for line in final_lines:
    line_lower = line.lower()
    for key in categories:
        if key in line_lower:
            category_count[categories[key]] += 1

interests = [cat for cat, _ in category_count.most_common(3)]

print("Top Interests:", interests)

"""**SUSPICIOUS ACTIVITY COUNT**"""

suspicious_keywords = [
    "hack", "hacker", "attack", "exploit", "malware",
    "crypto", "bitcoin", "torrent", "crack",
    "dark web", "leak", "breach", "phishing", "ddos"
]

suspicious_count = 0

for line in final_lines:
    for word in suspicious_keywords:
        if word in line.lower():
            suspicious_count += 1

print("Suspicious activity count:", suspicious_count)

"""**ADDING SUSPICIOUS LINES**



"""

test_suspicious = [
    "2024-03-10 02:30:00: how to hack wifi password",
    "2024-03-11 01:15:00: dark web access tutorial",
    "2024-03-12 03:45:00: torrent cracked software download"
]

final_lines.extend(test_suspicious)

"""**UPDATED COUNT**"""

suspicious_count = 0

for line in final_lines:
    for word in suspicious_keywords:
        if word in line.lower():
            suspicious_count += 1

print("Suspicious activity count:", suspicious_count)

"""**RISK LEVEL**"""

if suspicious_count >= 5:
    risk = "High"
elif suspicious_count >= 2:
    risk = "Medium"
else:
    risk = "Low"

print("Risk Level:", risk)

"""**NIGHT ACTIVITY**

"""

night_activity = 0

for line in final_lines:
    time_part = line.split(":")[0]   # get date + hour
    hour = int(time_part.split(" ")[1].split(":")[0])

    if 0 <= hour <= 4:
        night_activity += 1

if night_activity > 5:
    behavior = "Night-active"
else:
    behavior = "Normal"

print("Behavior:", behavior)

"""**INSTALLING TRANSFORMER**"""

!pip install -q transformers accelerate

"""**USING MODEL - TINY LLAMA**"""

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    device_map="auto"
)

"""**PROMPT**"""

prompt = f"""
<|system|>
You are a cybersecurity analyst and behavioral profiler.

Generate a realistic and professional psychological profile based only on given data.

Rules:
- Do NOT assign any name to the individual
- Do NOT make accusations (e.g., criminal, illegal activity)
- Keep analysis neutral and evidence-based
- Avoid exaggeration

<|user|>
Data:
Interests: {interests}
Behavior: {behavior}
Risk Level: {risk}
Suspicious Activity Count: {suspicious_count}

Generate:
- Psychological profile (detailed paragraph)
- Age range
-Location
- Interests explanation
- Behavioral insights
- Cybersecurity risk reasoning

<|assistant|>
"""

"""**RESULT**"""

result = pipe(prompt, max_new_tokens=500, do_sample=True)[0]["generated_text"]

print(result.split("<|assistant|>")[-1])

"""**EVALUATION REPORT**"""

true_age = "20-29"
true_interests = ["entertainment", "education", "social"]

def age_score(true, pred):
    if true == pred:
        return 1
    elif abs(int(true.split('-')[0]) - int(pred.split('-')[0])) == 10:
        return 0.5
    else:
        return 0

predicted_age = "20-29"  # from your output

print("Age Score:", age_score(true_age, predicted_age))

predicted_interests = interests

correct = len(set(true_interests) & set(predicted_interests))
total = max(len(true_interests), len(predicted_interests))

interest_score = correct / total

print("Interest Score:", interest_score)

print("\n Evaluation Results:\n")

print(f"{'Metric':<12}{'Truth':<40}{'Prediction':<40}{'Score'}")

# Age
age_s = age_score(true_age, predicted_age)
print(f"{'Age':<12}{true_age:<40}{predicted_age:<40}{age_s}")

# Interests
true_int_str = ", ".join(true_interests)
pred_int_str = ", ".join(predicted_interests)
print(f"{'Interests':<12}{true_int_str:<40}{pred_int_str:<40}{round(interest_score,2)}")

# Location (you can define this)
true_location = "Maryland"
predicted_location = "California"

location_score = 0  # since not matching

print(f"{'Location':<12}{true_location:<40}{predicted_location:<40}{location_score}")