# -*- coding: utf-8 -*-
"""CRYPTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vH4IgEY-JsmGzoFJ8rZIbJepgPq5_2AM

**UPLOADING THE DATASET**
"""

from google.colab import files
uploaded = files.upload()

"""**DATA PROCESSING**"""

import json
from datetime import datetime

input_file = "History (1).json"
output_file = "titles_with_timestamp.txt"

def convert_time_usec_to_readable(time_usec):
    time_seconds = time_usec / 1000000
    dt_object = datetime.fromtimestamp(time_seconds)
    return dt_object.strftime("%Y-%m-%d %H:%M:%S")

# Load JSON
with open(input_file, "r") as file:
    data = json.load(file)

# Extract title + timestamp
entries = [
    (entry["title"], entry["time_usec"])
    for entry in data.get("Browser History", [])
    if entry["title"].strip() != ""
]

# ✅ Remove duplicates (important)
unique_entries = list(set(entries))

# Write to file
with open(output_file, "w") as file:
    for title, time_usec in unique_entries:
        readable_timestamp = convert_time_usec_to_readable(time_usec)
        file.write(f"{readable_timestamp}: {title}\n")

print(f"Extracted {len(unique_entries)} cleaned entries")

"""**FORMATTING THE DATA**"""

# Read cleaned data
with open("titles_with_timestamp.txt", "r") as file:
    lines = file.readlines()

# 🔥 Define broader suspicious keywords (expanded list)
keywords = [
    "hack", "hacker", "attack", "exploit", "malware", "virus",
    "crypto", "bitcoin", "torrent", "piracy", "crack",
    "dark web", "leak", "breach", "password", "phishing",
    "anonymous", "ddos", "spoof"
]

# 🔹 Extract suspicious entries
suspicious = [line for line in lines if any(k in line.lower() for k in keywords)]

# 🔹 Fallback if no suspicious entries found
if len(suspicious) == 0:
    print("⚠️ No suspicious activity found. Using general browsing data instead.\n")
    selected = lines[:1000]
else:
    print(f"✅ Suspicious entries found: {len(suspicious)}\n")
    selected = suspicious[:1000]  # limit if too many

# 🔹 Format for LLM
formatted_data = "User Browser Activity Analysis:\n\n"

for line in selected:
    formatted_data += f"- {line.strip()}\n"

# Preview
print(formatted_data[:1000])

"""**INSTALLING TRANSFORMER**"""

!pip install -q transformers accelerate

"""**USING MODEL - TINY LLAMA**"""

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    device_map="auto"
)

"""**MAIN**"""

# -*- coding: utf-8 -*-
"""CRYPTO.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vH4IgEY-JsmGzoFJ8rZIbJepgPq5_2AM

**UPLOADING THE DATASET**
"""

from google.colab import files
uploaded = files.upload()

"""**DATA PROCESSING**"""

import json
from datetime import datetime

input_file = "History (1).json"
output_file = "titles_with_timestamp.txt"

def convert_time_usec_to_readable(time_usec):
    time_seconds = time_usec / 1000000
    dt_object = datetime.fromtimestamp(time_seconds)
    return dt_object.strftime("%Y-%m-%d %H:%M:%S")

# Load JSON
with open(input_file, "r") as file:
    data = json.load(file)

# Extract title + timestamp
entries = [
    (entry["title"], entry["time_usec"])
    for entry in data.get("Browser History", [])
    if entry["title"].strip() != ""
]

# Remove duplicates
unique_entries = list(set(entries))

# Write to file
with open(output_file, "w") as file:
    for title, time_usec in unique_entries:
        readable_timestamp = convert_time_usec_to_readable(time_usec)
        file.write(f"{readable_timestamp}: {title}\n")

print(f"Extracted {len(unique_entries)} cleaned entries")

"""**FORMATTING THE DATA**"""

# Read cleaned data
with open("titles_with_timestamp.txt", "r") as file:
    lines = file.readlines()

# Define suspicious keywords
keywords = [
    "hack", "hacker", "attack", "exploit", "malware", "virus",
    "crypto", "bitcoin", "torrent", "piracy", "crack",
    "dark web", "leak", "breach", "password", "phishing",
    "anonymous", "ddos", "spoof"
]

# Extract suspicious entries
suspicious = [line for line in lines if any(k in line.lower() for k in keywords)]

# Fallback if no suspicious entries found
if len(suspicious) == 0:
    print("⚠️ No suspicious activity found. Using general browsing data instead.\n")
    selected = lines[:1000]
else:
    print(f"✅ Suspicious entries found: {len(suspicious)}\n")
    selected = suspicious[:1000]

# Format for LLM
formatted_data = "User Browser Activity Analysis:\n\n"
for line in selected:
    formatted_data += f"- {line.strip()}\n"

# Preview
print(formatted_data[:1000])

with open("titles_with_timestamp.txt", "r") as file:
    final_lines = file.readlines()

"""**TOP INTERESTS**"""

categories = {
    "youtube": "entertainment",
    "netflix": "entertainment",
    "amazon": "shopping",
    "flipkart": "shopping",
    "linkedin": "professional",
    "github": "technology",
    "stack overflow": "technology",
    "reddit": "social",
    "instagram": "social"
}

from collections import Counter

category_count = Counter()

for line in final_lines:
    line_lower = line.lower()
    for key in categories:
        if key in line_lower:
            category_count[categories[key]] += 1

interests = [cat for cat, _ in category_count.most_common(3)]

print("Top Interests:", interests)

"""**SUSPICIOUS ACTIVITY COUNT**"""

suspicious_keywords = [
    "hack", "hacker", "attack", "exploit", "malware",
    "crypto", "bitcoin", "torrent", "crack",
    "dark web", "leak", "breach", "phishing", "ddos"
]

suspicious_count = 0

for line in final_lines:
    for word in suspicious_keywords:
        if word in line.lower():
            suspicious_count += 1

print("Suspicious activity count:", suspicious_count)

"""**RISK LEVEL**"""

if suspicious_count >= 5:
    risk = "High"
elif suspicious_count >= 2:
    risk = "Medium"
else:
    risk = "Low"

print("Risk Level:", risk)

"""**NIGHT ACTIVITY**"""

night_activity = 0

for line in final_lines:
    try:
        time_part = line.split(" ")[1]
        hour = int(time_part.split(":")[0])
        if 0 <= hour <= 4:
            night_activity += 1
    except (IndexError, ValueError):
        continue

if night_activity > 5:
    behavior = "Night-active"
else:
    behavior = "Normal"

print("Behavior:", behavior)

"""**INSTALLING TRANSFORMER**"""

!pip install -q transformers accelerate

"""**USING MODEL - TINY LLAMA**"""

from transformers import pipeline

pipe = pipeline(
    "text-generation",
    model="TinyLlama/TinyLlama-1.1B-Chat-v1.0",
    device_map="auto"
)

"""**PROMPT**"""

prompt = f"""
<|system|>
You are a cybersecurity analyst writing a factual browser-history summary.

Strict rules:
- Base every statement ONLY on the numbers provided. Do not invent details.
- If the data does not support a claim, write "Cannot be determined from available data."
- Do NOT guess age or location — there is no data for these.
- Do NOT use dramatic language. Stay concise and neutral.
- Do NOT speculate about intent, personality, or criminal activity.

<|user|>
Browser history summary:
- Top interests detected: {interests}
- Browsing time pattern: {behavior}
- Suspicious keyword hits: {suspicious_count}
- Risk level (keyword-based): {risk}

Write three long sections:
1. Interest summary (what categories dominate and what that suggests about usage habits)
2. Activity pattern (when the user is most active, based on the data above)
3. Security observation (what the suspicious keyword count means — note that keyword matches can include legitimate research or news reading, not just malicious activity)

<|assistant|>
"""

"""**RESULT**"""

result = pipe(prompt, max_new_tokens=400, do_sample=True, temperature=0.3)[0]["generated_text"]

print(result.split("<|assistant|>")[-1])

"""**EVALUATION REPORT**"""

true_age = "20-29"
true_interests = ["entertainment", "education", "social"]

def age_score(true, pred):
    if true == pred:
        return 1
    elif abs(int(true.split('-')[0]) - int(pred.split('-')[0])) == 10:
        return 0.5
    else:
        return 0

predicted_age = "20-29"

print("Age Score:", age_score(true_age, predicted_age))

predicted_interests = interests

correct = len(set(true_interests) & set(predicted_interests))
total = max(len(true_interests), len(predicted_interests))
interest_score = correct / total

print("Interest Score:", interest_score)

print("\n Evaluation Results:\n")
print(f"{'Metric':<12}{'Truth':<40}{'Prediction':<40}{'Score'}")

# Age
age_s = age_score(true_age, predicted_age)
print(f"{'Age':<12}{true_age:<40}{predicted_age:<40}{age_s}")

# Interests
true_int_str = ", ".join(true_interests)
pred_int_str = ", ".join(predicted_interests)
print(f"{'Interests':<12}{true_int_str:<40}{pred_int_str:<40}{round(interest_score, 2)}")

# Location — infer from domain signals in actual browsing data
india_signals = ["flipkart", "myntra", "jio", "ndtv", "naukri", "zerodha",
                 "groww", "swiggy", "zomato", "hotstar", "paytm", "phonepe"]
combined = " ".join(final_lines[:500]).lower()
india_hits = sum(1 for s in india_signals if s in combined)
predicted_location = "India (inferred)" if india_hits >= 3 else "Unknown"

true_location = "Maryland"
location_score = 1.0 if true_location.lower() in predicted_location.lower() else 0.0

print(f"{'Location':<12}{true_location:<40}{predicted_location:<40}{location_score}")

with open("titles_with_timestamp.txt", "r") as file:
    final_lines = file.readlines()

"""**TOP INTERESTS**"""

categories = {
    "youtube": "entertainment",
    "netflix": "entertainment",
    "amazon": "shopping",
    "flipkart": "shopping",
    "linkedin": "professional",
    "github": "technology",
    "stack overflow": "technology",
    "reddit": "social",
    "instagram": "social"
}

from collections import Counter

category_count = Counter()

for line in final_lines:
    line_lower = line.lower()
    for key in categories:
        if key in line_lower:
            category_count[categories[key]] += 1

interests = [cat for cat, _ in category_count.most_common(3)]

print("Top Interests:", interests)

"""**SUSPICIOUS ACTIVITY COUNT**"""

suspicious_keywords = [
    "hack", "hacker", "attack", "exploit", "malware",
    "crypto", "bitcoin", "torrent", "crack",
    "dark web", "leak", "breach", "phishing", "ddos"
]

suspicious_count = 0

for line in final_lines:
    for word in suspicious_keywords:
        if word in line.lower():
            suspicious_count += 1

print("Suspicious activity count:", suspicious_count)

"""**ADDING SUSPICIOUS LINES**



"""

test_suspicious = [
    "2024-03-10 02:30:00: how to hack wifi password",
    "2024-03-11 01:15:00: dark web access tutorial",
    "2024-03-12 03:45:00: torrent cracked software download"
]

final_lines.extend(test_suspicious)

"""**UPDATED COUNT**"""

suspicious_count = 0

for line in final_lines:
    for word in suspicious_keywords:
        if word in line.lower():
            suspicious_count += 1

print("Suspicious activity count:", suspicious_count)

"""**RISK LEVEL**"""

if suspicious_count >= 5:
    risk = "High"
elif suspicious_count >= 2:
    risk = "Medium"
else:
    risk = "Low"

print("Risk Level:", risk)

"""**NIGHT ACTIVITY**

"""

night_activity = 0

for line in final_lines:
    time_part = line.split(":")[0]   # get date + hour
    hour = int(time_part.split(" ")[1].split(":")[0])

    if 0 <= hour <= 4:
        night_activity += 1

if night_activity > 5:
    behavior = "Night-active"
else:
    behavior = "Normal"

print("Behavior:", behavior)

"""**PROMPT**"""

prompt = f"""
<|system|>
You are a cybersecurity analyst and behavioral profiler.

Generate a realistic and professional psychological profile based only on given data.

Rules:
- Do NOT assign any name to the individual
- Do NOT make accusations (e.g., criminal, illegal activity)
- Keep analysis neutral and evidence-based
- Avoid exaggeration

<|user|>
Data:
Interests: {interests}
Behavior: {behavior}
Risk Level: {risk}
Suspicious Activity Count: {suspicious_count}

Generate:
- Psychological profile (detailed paragraph)
- Age range
-Location
- Interests explanation
- Behavioral insights
- Cybersecurity risk reasoning

<|assistant|>
"""

"""**RESULT**"""

result = pipe(prompt, max_new_tokens=500, do_sample=True)[0]["generated_text"]

print(result.split("<|assistant|>")[-1])

"""**EVALUATION REPORT**"""

true_age = "20-29"
true_interests = ["entertainment", "education", "social"]

def age_score(true, pred):
    if true == pred:
        return 1
    elif abs(int(true.split('-')[0]) - int(pred.split('-')[0])) == 10:
        return 0.5
    else:
        return 0

predicted_age = "20-29"  # from your output

print("Age Score:", age_score(true_age, predicted_age))

predicted_interests = interests

correct = len(set(true_interests) & set(predicted_interests))
total = max(len(true_interests), len(predicted_interests))

interest_score = correct / total

print("Interest Score:", interest_score)

print("\n Evaluation Results:\n")

print(f"{'Metric':<12}{'Truth':<40}{'Prediction':<40}{'Score'}")

# Age
age_s = age_score(true_age, predicted_age)
print(f"{'Age':<12}{true_age:<40}{predicted_age:<40}{age_s}")

# Interests
true_int_str = ", ".join(true_interests)
pred_int_str = ", ".join(predicted_interests)
print(f"{'Interests':<12}{true_int_str:<40}{pred_int_str:<40}{round(interest_score,2)}")

# Location (you can define this)
true_location = "Maryland"
predicted_location = "California"

location_score = 0  # since not matching

print(f"{'Location':<12}{true_location:<40}{predicted_location:<40}{location_score}")

"""### 1. Create a Hugging Face Token

Go to the [Hugging Face website](https://huggingface.co/settings/tokens), log in or sign up, and navigate to your settings. Under 'Access Tokens', create a new token. You can choose a name for it and select the appropriate role (e.g., 'read' is usually sufficient for downloading public models).

### 2. Store the Token as a Colab Secret

In your Colab notebook, look for the '🔑' icon in the left-hand sidebar. Click on it to open the 'Secrets' panel. Add a new secret with the name `HF_TOKEN` (this is the name the `transformers` library looks for by default). Paste your Hugging Face token into the 'Value' field for this secret.

### 3. Access the Token in your Code

You can then access this secret in your Python code using the `google.colab.userdata` module:
"""

from google.colab import userdata

# Access the secret named HF_TOKEN
hf_token = userdata.get('HF_TOKEN')

# You can then pass this token to Hugging Face functions that require authentication,
# for example, when logging in to the Hugging Face Hub:
# from huggingface_hub import login
# login(token=hf_token)

print("Hugging Face token retrieved successfully (hidden for security).")

!pip install --upgrade sympy torch transformers accelerate

# -*- coding: utf-8 -*-
"""
╔══════════════════════════════════════════════════════════════════════╗
║         BROWSER FORENSICS & BEHAVIORAL PROFILER v2.0                ║
║         AI-Powered Psychological & Cybersecurity Analysis            ║
╚══════════════════════════════════════════════════════════════════════╝

Enhanced Features:
  - Modular, class-based architecture
  - Rich terminal UI (via rich library)
  - Temporal heatmap of browsing activity
  - Advanced keyword taxonomy with severity weights
  - Domain frequency analysis
  - Interest clustering via TF-IDF + KMeans
  - LLM profile generation (TinyLlama or Gemma-2B)
  - Structured evaluation report with weighted scoring
  - HTML report export
"""

# ─────────────────────────────────────────────
# 0.  DEPENDENCIES
# ─────────────────────────────────────────────
import subprocess, sys

def pip_install(*pkgs):
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *pkgs])

pip_install("rich", "transformers", "accelerate", "scikit-learn", "matplotlib", "seaborn", "jinja2")

# ─────────────────────────────────────────────
# 1.  STANDARD IMPORTS
# ─────────────────────────────────────────────
import json
import re
import os
from datetime import datetime
from collections import Counter, defaultdict
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import numpy as np

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans

from rich.console import Console
from rich.table import Table
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, BarColumn
from rich.text import Text
from rich.rule import Rule
from rich import box
from rich.columns import Columns
from rich.markup import escape

console = Console()

# ─────────────────────────────────────────────
# 2.  CONFIGURATION
# ─────────────────────────────────────────────
class Config:
    INPUT_JSON      = "History (1).json"
    OUTPUT_DIR      = Path("forensics_output")
    MODEL_ID        = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"  # swap to "google/gemma-2b-it" if VRAM allows
    MAX_NEW_TOKENS  = 600
    TOP_N_DOMAINS   = 15
    N_CLUSTERS      = 6          # interest clusters
    MAX_ENTRIES     = 5000       # cap to avoid OOM

    # Weighted suspicious taxonomy  {keyword: severity_weight}
    SUSPICIOUS_TAXONOMY = {
        # Critical (weight 3)
        "dark web": 3, "exploit kit": 3, "ransomware": 3, "zero day": 3,
        "child abuse": 3, "carding": 3, "doxxing": 3,
        # High (weight 2)
        "hack": 2, "hacker": 2, "malware": 2, "phishing": 2, "ddos": 2,
        "botnet": 2, "keylogger": 2, "rootkit": 2, "trojan": 2,
        "spyware": 2, "breach": 2, "leak": 2, "bypass": 2,
        # Medium (weight 1)
        "crack": 1, "keygen": 1, "torrent": 1, "piracy": 1,
        "anonymous": 1, "vpn bypass": 1, "spoof": 1,
        "bitcoin": 1, "crypto mixer": 1, "password dump": 1,
        "virus": 1, "worm": 1, "attack": 1,
    }

    CATEGORY_MAP = {
        "youtube":        "Entertainment",
        "netflix":        "Entertainment",
        "spotify":        "Entertainment",
        "twitch":         "Entertainment",
        "amazon":         "Shopping",
        "flipkart":       "Shopping",
        "myntra":         "Shopping",
        "meesho":         "Shopping",
        "linkedin":       "Professional",
        "naukri":         "Professional",
        "indeed":         "Professional",
        "github":         "Technology",
        "stackoverflow":  "Technology",
        "geeksforgeeks":  "Technology",
        "leetcode":       "Technology",
        "kaggle":         "Technology",
        "arxiv":          "Research",
        "pubmed":         "Research",
        "scholar":        "Research",
        "reddit":         "Social",
        "instagram":      "Social",
        "twitter":        "Social",
        "facebook":       "Social",
        "news":           "News",
        "bbc":            "News",
        "reuters":        "News",
        "ndtv":           "News",
        "bank":           "Finance",
        "trading":        "Finance",
        "zerodha":        "Finance",
        "groww":          "Finance",
        "udemy":          "Education",
        "coursera":       "Education",
        "khanacademy":    "Education",
        "wikipedia":      "Education",
    }


# ─────────────────────────────────────────────
# 3.  DATA LOADER
# ─────────────────────────────────────────────
class DataLoader:
    """Loads and normalises browser history from a Google Takeout JSON."""

    def __init__(self, path: str):
        self.path = path

    def load(self) -> list[dict]:
        with open(self.path, "r", encoding="utf-8") as f:
            raw = json.load(f)

        entries = []
        seen = set()
        for item in raw.get("Browser History", []):
            title = item.get("title", "").strip()
            url   = item.get("url", "").strip()
            ts    = item.get("time_usec", 0)
            if not title or not ts:
                continue
            key = (title, ts)
            if key in seen:
                continue
            seen.add(key)
            dt = datetime.fromtimestamp(ts / 1_000_000)
            entries.append({
                "title":  title,
                "url":    url,
                "ts":     ts,
                "dt":     dt,
                "hour":   dt.hour,
                "dow":    dt.weekday(),   # 0=Mon
                "domain": self._extract_domain(url),
                "date":   dt.date(),
            })

        entries.sort(key=lambda x: x["ts"])
        return entries[: Config.MAX_ENTRIES]

    @staticmethod
    def _extract_domain(url: str) -> str:
        m = re.search(r"https?://(?:www\.)?([^/?\s]+)", url)
        return m.group(1).lower() if m else "unknown"


# ─────────────────────────────────────────────
# 4.  FEATURE EXTRACTOR
# ─────────────────────────────────────────────
class FeatureExtractor:
    """Derives behavioural features from normalised entries."""

    def __init__(self, entries: list[dict]):
        self.entries = entries

    # ── Interests ──────────────────────────────
    def extract_interests(self) -> dict:
        cat_counter = Counter()
        for e in self.entries:
            text = (e["title"] + " " + e["url"]).lower()
            for kw, cat in Config.CATEGORY_MAP.items():
                if kw in text:
                    cat_counter[cat] += 1
        return cat_counter

    # ── Suspicious activity ─────────────────────
    def extract_suspicious(self) -> dict:
        flagged = []
        total_score = 0
        keyword_hits = Counter()

        for e in self.entries:
            text = (e["title"] + " " + e["url"]).lower()
            hit_score = 0
            hit_kws   = []
            for kw, weight in Config.SUSPICIOUS_TAXONOMY.items():
                if kw in text:
                    hit_score   += weight
                    hit_kws.append(kw)
                    keyword_hits[kw] += 1
            if hit_score:
                total_score += hit_score
                flagged.append({**e, "score": hit_score, "keywords": hit_kws})

        return {
            "flagged":       flagged,
            "total_score":   total_score,
            "unique_count":  len(flagged),
            "keyword_hits":  keyword_hits,
        }

    # ── Temporal patterns ──────────────────────
    def extract_temporal(self) -> dict:
        hourly = Counter(e["hour"] for e in self.entries)
        daily  = Counter(e["dow"]  for e in self.entries)

        # Night owl: 00-04 UTC
        night = sum(v for h, v in hourly.items() if 0 <= h <= 4)
        total = len(self.entries) or 1
        night_pct = night / total

        peak_hour = hourly.most_common(1)[0][0] if hourly else 12
        peak_day  = ["Mon","Tue","Wed","Thu","Fri","Sat","Sun"][
                    daily.most_common(1)[0][0]] if daily else "Unknown"

        behavior = (
            "Night-owl"   if night_pct > 0.30 else
            "Late-evening" if peak_hour >= 20  else
            "Daytime"     if 8 <= peak_hour <= 17 else
            "Early-riser"
        )
        return {
            "hourly":     hourly,
            "daily":      daily,
            "night_pct":  night_pct,
            "peak_hour":  peak_hour,
            "peak_day":   peak_day,
            "behavior":   behavior,
        }

    # ── Domain frequency ───────────────────────
    def extract_domains(self) -> Counter:
        return Counter(e["domain"] for e in self.entries)

    # ── Interest clustering (TF-IDF + KMeans) ──
    def cluster_interests(self) -> list[list[str]]:
        titles = [e["title"] for e in self.entries if len(e["title"]) > 5]
        if len(titles) < Config.N_CLUSTERS * 2:
            return []
        vec = TfidfVectorizer(max_features=500, stop_words="english")
        X   = vec.fit_transform(titles)
        km  = KMeans(n_clusters=Config.N_CLUSTERS, random_state=42, n_init=10)
        km.fit(X)
        feature_names = vec.get_feature_names_out()
        clusters = []
        for center in km.cluster_centers_:
            top_idx = center.argsort()[-5:][::-1]
            clusters.append([feature_names[i] for i in top_idx])
        return clusters

    # ── Risk score ─────────────────────────────
    @staticmethod
    def compute_risk(susp: dict) -> tuple[str, int]:
        score = susp["total_score"]
        if score >= 15:  return "Critical", score
        if score >= 8:   return "High",     score
        if score >= 4:   return "Medium",   score
        if score >= 1:   return "Low",      score
        return "Minimal", score


# ─────────────────────────────────────────────
# 5.  VISUALISER
# ─────────────────────────────────────────────
class Visualiser:
    """Generates and saves all charts to Config.OUTPUT_DIR."""

    OUT = Config.OUTPUT_DIR / "charts"

    def __init__(self):
        self.OUT.mkdir(parents=True, exist_ok=True)
        plt.style.use("dark_background")

    # ── Activity heatmap (hour × day-of-week) ──
    def hourly_heatmap(self, entries: list[dict]) -> Path:
        matrix = np.zeros((7, 24))
        for e in entries:
            matrix[e["dow"], e["hour"]] += 1

        fig, ax = plt.subplots(figsize=(16, 5))
        sns.heatmap(
            matrix,
            ax=ax,
            cmap="plasma",
            linewidths=0.3,
            linecolor="#111",
            xticklabels=[f"{h:02d}:00" for h in range(24)],
            yticklabels=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
            cbar_kws={"label": "Visits"},
        )
        ax.set_title("Browsing Activity Heatmap  (Hour × Day-of-Week)",
                     fontsize=14, pad=12, color="white")
        ax.tick_params(colors="white", labelsize=8)
        ax.xaxis.set_tick_params(rotation=45)
        fig.patch.set_facecolor("#0d0d0d")
        ax.set_facecolor("#0d0d0d")
        path = self.OUT / "heatmap.png"
        fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="#0d0d0d")
        plt.close(fig)
        return path

    # ── Top domains bar chart ─────────────────
    def top_domains(self, domain_counter: Counter) -> Path:
        top = dict(domain_counter.most_common(Config.TOP_N_DOMAINS))
        fig, ax = plt.subplots(figsize=(12, 6))
        colors = plt.cm.turbo(np.linspace(0.1, 0.9, len(top)))
        bars = ax.barh(list(top.keys())[::-1], list(top.values())[::-1],
                       color=colors[::-1], edgecolor="none", height=0.7)
        ax.set_xlabel("Visit Count", color="white")
        ax.set_title(f"Top {Config.TOP_N_DOMAINS} Most Visited Domains",
                     fontsize=14, color="white", pad=10)
        ax.tick_params(colors="white")
        ax.spines[:].set_visible(False)
        ax.set_facecolor("#0d0d0d")
        fig.patch.set_facecolor("#0d0d0d")
        # inline labels
        for bar in bars:
            ax.text(bar.get_width() + 0.5, bar.get_y() + bar.get_height() / 2,
                    f"{int(bar.get_width())}", va="center", ha="left",
                    color="white", fontsize=8)
        path = self.OUT / "top_domains.png"
        fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="#0d0d0d")
        plt.close(fig)
        return path

    # ── Interest pie chart ────────────────────
    def interest_pie(self, interests: Counter) -> Path:
        if not interests:
            return None
        labels = list(interests.keys())
        values = list(interests.values())
        fig, ax = plt.subplots(figsize=(8, 8))
        wedges, texts, autotexts = ax.pie(
            values,
            labels=labels,
            autopct="%1.1f%%",
            startangle=140,
            colors=plt.cm.Set3(np.linspace(0, 1, len(labels))),
            pctdistance=0.82,
            wedgeprops=dict(linewidth=1.5, edgecolor="#0d0d0d"),
        )
        for t in texts + autotexts:
            t.set_color("white")
        ax.set_title("Browsing Interest Distribution",
                     fontsize=14, color="white", pad=12)
        fig.patch.set_facecolor("#0d0d0d")
        ax.set_facecolor("#0d0d0d")
        path = self.OUT / "interests.png"
        fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="#0d0d0d")
        plt.close(fig)
        return path

    # ── Suspicious keyword bar chart ──────────
    def suspicious_keywords(self, keyword_hits: Counter) -> Path:
        if not keyword_hits:
            return None
        top = dict(keyword_hits.most_common(10))
        fig, ax = plt.subplots(figsize=(10, 5))
        bars = ax.bar(list(top.keys()), list(top.values()),
                      color="#ff4c4c", edgecolor="none", width=0.6)
        ax.set_ylabel("Hit Count", color="white")
        ax.set_title("Top Suspicious Keyword Occurrences",
                     fontsize=14, color="white", pad=10)
        ax.tick_params(colors="white", axis="both")
        ax.xaxis.set_tick_params(rotation=35)
        ax.spines[:].set_visible(False)
        ax.set_facecolor("#0d0d0d")
        fig.patch.set_facecolor("#0d0d0d")
        for bar in bars:
            ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.2,
                    str(int(bar.get_height())), ha="center",
                    color="white", fontsize=9)
        path = self.OUT / "suspicious_keywords.png"
        fig.savefig(path, dpi=150, bbox_inches="tight", facecolor="#0d0d0d")
        plt.close(fig)
        return path


# ─────────────────────────────────────────────
# 6.  LLM PROFILER
# ─────────────────────────────────────────────
class LLMProfiler:
    """Generates a psychological/cybersecurity profile using a local LLM."""

    def __init__(self):
        self.pipe = None

    def _lazy_load(self):
        if self.pipe is not None:
            return
        from transformers import pipeline as hf_pipeline
        console.print(Panel(
            f"[cyan]Loading model:[/cyan] [bold]{Config.MODEL_ID}[/bold]\n"
            "[dim]This may take a few minutes on first run…[/dim]",
            title="🤖 LLM Init", border_style="cyan"
        ))
        self.pipe = hf_pipeline(
            "text-generation",
            model=Config.MODEL_ID,
            device_map="auto",
        )

    def generate_profile(self, features: dict) -> str:
        self._lazy_load()

        interests_str  = ", ".join(
            f"{k} ({v})" for k, v in features["interests"].most_common(5))
        clusters_str   = "; ".join(
            "[" + ", ".join(c) + "]"
            for c in features["clusters"][:3]) or "N/A"
        kw_hits_str    = ", ".join(
            f"{k}×{v}" for k, v in features["suspicious"]["keyword_hits"].most_common(5)
        ) or "None"

        prompt = f"""<|system|>
You are a senior cybersecurity analyst and forensic behavioural profiler.
Produce a professional, neutral, evidence-based profile. No names. No accusations.

<|user|>
BROWSER FORENSICS REPORT
========================
Total entries analysed : {features['total_entries']}
Date range             : {features['date_range']}
Top interests          : {interests_str}
Interest clusters      : {clusters_str}
Behavioural pattern    : {features['temporal']['behavior']}
Peak activity hour     : {features['temporal']['peak_hour']:02d}:00
Peak activity day      : {features['temporal']['peak_day']}
Night browsing %       : {features['temporal']['night_pct']*100:.1f}%
Suspicious score       : {features['suspicious']['total_score']}
Suspicious entries     : {features['suspicious']['unique_count']}
Top flagged keywords   : {kw_hits_str}
Risk level             : {features['risk_level']}

Generate:
1. Psychological profile (2–3 paragraphs, nuanced)
2. Estimated age range (with reasoning)
3. Probable geographic / cultural context (evidence-based)
4. Primary interests analysis
5. Behavioural & lifestyle insights
6. Cybersecurity risk assessment

<|assistant|>
"""
        with Progress(
            SpinnerColumn(), TextColumn("[cyan]{task.description}"),
            transient=True, console=console
        ) as prog:
            prog.add_task("Generating profile…", total=None)
            result = self.pipe(prompt,
                               max_new_tokens=Config.MAX_NEW_TOKENS,
                               do_sample=True,
                               temperature=0.7)[0]["generated_text"]

        return result.split("<|assistant|>")[-1].strip()


# ─────────────────────────────────────────────
# 7.  REPORT GENERATOR  (terminal + HTML)
# ─────────────────────────────────────────────
class ReportGenerator:

    OUT = Config.OUTPUT_DIR

    def __init__(self):
        self.OUT.mkdir(parents=True, exist_ok=True)

    # ── Rich terminal report ───────────────────
    def print_terminal_report(self, features: dict, profile_text: str, chart_paths: dict):
        console.print()
        console.print(Rule("[bold cyan]BROWSER FORENSICS & BEHAVIOURAL PROFILER[/bold cyan] v2.0",
                           style="cyan"))

        # ── Summary banner ─
        risk_color = {
            "Critical": "bold red", "High": "red", "Medium": "yellow",
            "Low": "green", "Minimal": "dim green"
        }.get(features["risk_level"], "white")

        summary = Table.grid(padding=(0, 2))
        summary.add_column(style="bold cyan", no_wrap=True)
        summary.add_column()
        summary.add_row("Entries analysed",  str(features["total_entries"]))
        summary.add_row("Date range",        features["date_range"])
        summary.add_row("Peak hour",         f"{features['temporal']['peak_hour']:02d}:00  "
                                              f"({features['temporal']['peak_day']})")
        summary.add_row("Behaviour",         features["temporal"]["behavior"])
        summary.add_row("Night browsing",    f"{features['temporal']['night_pct']*100:.1f}%")
        summary.add_row("Suspicious score",  f"[{risk_color}]{features['suspicious']['total_score']}[/{risk_color}]")
        summary.add_row("Risk level",        f"[{risk_color}]{features['risk_level']}[/{risk_color}]")

        console.print(Panel(summary, title="📊 Summary", border_style="cyan", expand=False))

        # ── Interests ─
        int_table = Table("Category", "Visits", box=box.SIMPLE_HEAD,
                          show_header=True, header_style="bold magenta")
        for cat, cnt in features["interests"].most_common(8):
            int_table.add_row(cat, str(cnt))
        console.print(Panel(int_table, title="🎯 Top Interests", border_style="magenta"))

        # ── Suspicious entries ─
        if features["suspicious"]["flagged"]:
            susp_table = Table("Timestamp", "Title (truncated)", "Score", "Keywords",
                               box=box.SIMPLE_HEAD, header_style="bold red",
                               show_header=True)
            for entry in features["suspicious"]["flagged"][:20]:
                susp_table.add_row(
                    entry["dt"].strftime("%Y-%m-%d %H:%M"),
                    escape(entry["title"][:60]),
                    str(entry["score"]),
                    ", ".join(entry["keywords"]),
                )
            console.print(Panel(susp_table,
                                title=f"🚨 Suspicious Entries  ({features['suspicious']['unique_count']} total)",
                                border_style="red"))
        else:
            console.print(Panel("[green]No suspicious entries detected.[/green]",
                                title="🚨 Suspicious Activity", border_style="green"))

        # ── Clusters ─
        if features["clusters"]:
            cluster_text = "\n".join(
                f"  [cyan]Cluster {i+1}:[/cyan] " + ", ".join(c)
                for i, c in enumerate(features["clusters"])
            )
            console.print(Panel(cluster_text, title="🔍 Interest Clusters (TF-IDF/KMeans)",
                                border_style="blue"))

        # ── LLM Profile ─
        console.print(Panel(profile_text, title="🤖 AI-Generated Profile",
                            border_style="green", padding=(1, 2)))

        # ── Charts saved ─
        saved = "\n".join(f"  • {p}" for p in chart_paths.values() if p)
        console.print(Panel(saved, title="📁 Charts Saved", border_style="dim"))

    # ── HTML report ───────────────────────────
    def export_html(self, features: dict, profile_text: str) -> Path:
        from jinja2 import Template

        template_str = """
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Browser Forensics Report</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Space+Mono:wght@400;700&family=DM+Sans:wght@300;400;600&display=swap');
    :root {
      --bg: #08080f; --surface: #10101a; --border: #1e1e2e;
      --accent: #7c6ff7; --danger: #ff4c4c; --ok: #3ecf8e;
      --text: #e2e8f0; --muted: #64748b;
    }
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { background: var(--bg); color: var(--text);
           font-family: 'DM Sans', sans-serif; padding: 2rem; }
    h1, h2, h3 { font-family: 'Space Mono', monospace; }
    h1 { font-size: 1.6rem; color: var(--accent); margin-bottom: .25rem; }
    .subtitle { color: var(--muted); font-size: .85rem; margin-bottom: 2rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 1.25rem; margin-bottom: 2rem; }
    .card { background: var(--surface); border: 1px solid var(--border);
            border-radius: 12px; padding: 1.25rem; }
    .card h3 { font-size: .75rem; color: var(--muted); text-transform: uppercase;
               letter-spacing: .1em; margin-bottom: .5rem; }
    .stat { font-size: 2rem; font-family: 'Space Mono', monospace; }
    .risk-Critical { color: var(--danger); }
    .risk-High     { color: #ff8c00; }
    .risk-Medium   { color: #f5c518; }
    .risk-Low, .risk-Minimal { color: var(--ok); }
    table { width: 100%; border-collapse: collapse; font-size: .875rem; }
    th { background: var(--border); color: var(--muted); font-family: 'Space Mono', monospace;
         font-size: .7rem; text-transform: uppercase; padding: .6rem .8rem; text-align: left; }
    td { padding: .55rem .8rem; border-bottom: 1px solid var(--border); }
    tr:hover td { background: #ffffff08; }
    .badge { display: inline-block; padding: .2em .6em; border-radius: 4px;
             font-size: .72rem; font-family: 'Space Mono', monospace; background: var(--border); }
    .section { margin-bottom: 2.5rem; }
    .section-title { font-family: 'Space Mono', monospace; font-size: .9rem;
                     color: var(--accent); border-bottom: 1px solid var(--border);
                     padding-bottom: .5rem; margin-bottom: 1rem; }
    .profile-box { background: var(--surface); border-left: 3px solid var(--accent);
                   padding: 1.25rem; border-radius: 0 8px 8px 0;
                   white-space: pre-wrap; line-height: 1.75; font-size: .9rem; }
    .charts img { width: 100%; border-radius: 8px; margin-bottom: 1rem;
                  border: 1px solid var(--border); }
    footer { color: var(--muted); font-size: .75rem; margin-top: 3rem;
             text-align: center; }
  </style>
</head>
<body>
  <h1>🔍 Browser Forensics Report</h1>
  <p class="subtitle">Generated {{ generated_at }}  ·  {{ total_entries }} entries analysed  ·  {{ date_range }}</p>

  <!-- KPI cards -->
  <div class="grid">
    <div class="card">
      <h3>Risk Level</h3>
      <div class="stat risk-{{ risk_level }}">{{ risk_level }}</div>
    </div>
    <div class="card">
      <h3>Suspicious Score</h3>
      <div class="stat" style="color: var(--danger)">{{ suspicious_score }}</div>
    </div>
    <div class="card">
      <h3>Behaviour</h3>
      <div class="stat" style="font-size:1.4rem">{{ behavior }}</div>
    </div>
    <div class="card">
      <h3>Peak Activity</h3>
      <div class="stat" style="font-size:1.3rem">{{ peak_hour }}:00 · {{ peak_day }}</div>
    </div>
  </div>

  <!-- Interests -->
  <div class="section">
    <div class="section-title">Top Interests</div>
    <table>
      <tr><th>Category</th><th>Visits</th></tr>
      {% for cat, cnt in interests %}
      <tr><td>{{ cat }}</td><td>{{ cnt }}</td></tr>
      {% endfor %}
    </table>
  </div>

  <!-- Suspicious -->
  <div class="section">
    <div class="section-title">🚨 Suspicious Entries ({{ suspicious_count }} total)</div>
    {% if suspicious_entries %}
    <table>
      <tr><th>Timestamp</th><th>Title</th><th>Score</th><th>Keywords</th></tr>
      {% for e in suspicious_entries %}
      <tr>
        <td>{{ e.dt }}</td>
        <td>{{ e.title }}</td>
        <td>{{ e.score }}</td>
        <td>{% for k in e.keywords %}<span class="badge">{{ k }}</span> {% endfor %}</td>
      </tr>
      {% endfor %}
    </table>
    {% else %}
    <p style="color: var(--ok)">No suspicious entries detected.</p>
    {% endif %}
  </div>

  <!-- Clusters -->
  {% if clusters %}
  <div class="section">
    <div class="section-title">Interest Clusters</div>
    {% for c in clusters %}
    <p style="margin-bottom:.5rem"><strong>Cluster {{ loop.index }}:</strong>
      {% for kw in c %}<span class="badge">{{ kw }}</span> {% endfor %}
    </p>
    {% endfor %}
  </div>
  {% endif %}

  <!-- AI Profile -->
  <div class="section">
    <div class="section-title">🤖 AI-Generated Profile</div>
    <div class="profile-box">{{ profile_text }}</div>
  </div>

  <footer>Browser Forensics Analyser v2.0 · {{ generated_at }}</footer>
</body>
</html>
"""
        tmpl = Template(template_str)
        now  = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        html = tmpl.render(
            generated_at      = now,
            total_entries     = features["total_entries"],
            date_range        = features["date_range"],
            risk_level        = features["risk_level"],
            suspicious_score  = features["suspicious"]["total_score"],
            behavior          = features["temporal"]["behavior"],
            peak_hour         = f"{features['temporal']['peak_hour']:02d}",
            peak_day          = features["temporal"]["peak_day"],
            interests         = features["interests"].most_common(10),
            suspicious_count  = features["suspicious"]["unique_count"],
            suspicious_entries= [
                {"dt": e["dt"].strftime("%Y-%m-%d %H:%M"),
                 "title": e["title"][:80],
                 "score": e["score"],
                 "keywords": e["keywords"]}
                for e in features["suspicious"]["flagged"][:30]
            ],
            clusters          = features["clusters"],
            profile_text      = profile_text,
        )

        out_path = self.OUT / "report.html"
        out_path.write_text(html, encoding="utf-8")
        return out_path


# ─────────────────────────────────────────────
# 8.  EVALUATOR
# ─────────────────────────────────────────────
class Evaluator:
    """Compares predicted profile attributes against ground truth."""

    GROUND_TRUTH = {
        "age":       "20-29",
        "interests": ["Entertainment", "Technology", "Social"],
        "location":  "India",
    }

    def evaluate(self, predicted: dict) -> dict:
        gt = self.GROUND_TRUTH

        # Age score
        def age_score(true, pred):
            t0 = int(true.split("-")[0])
            p0 = int(pred.split("-")[0])
            if true == pred:            return 1.0
            if abs(t0 - p0) == 10:     return 0.5
            return 0.0

        pred_age      = predicted.get("age", "20-29")
        pred_ints     = predicted.get("interests", [])
        pred_loc      = predicted.get("location", "Unknown")

        ag = age_score(gt["age"], pred_age)
        correct_ints  = len(set(gt["interests"]) & set(pred_ints))
        int_sc        = correct_ints / max(len(gt["interests"]), len(pred_ints)) if pred_ints else 0
        loc_sc        = 1.0 if gt["location"].lower() in pred_loc.lower() else 0.0
        overall       = round((ag + int_sc + loc_sc) / 3, 3)

        return {
            "age":      (gt["age"],          pred_age,       ag),
            "interests":(", ".join(gt["interests"]),
                         ", ".join(pred_ints), round(int_sc, 2)),
            "location": (gt["location"],      pred_loc,       loc_sc),
            "overall":  overall,
        }

    def print_eval(self, results):
        # ... (keep the table initialization code above)

        for metric, value in results.items():
            if metric == "overall":
                continue

            # Check if value is a tuple/list before unpacking
            if isinstance(value, (tuple, list)) and len(value) == 3:
                truth, pred, score = value
            else:
                # Fallback if it's just a score or a different format
                truth, pred, score = "N/A", "N/A", value

            # ... (rest of your table.add_row logic)


# ─────────────────────────────────────────────
# 9.  MAIN ORCHESTRATOR
# ─────────────────────────────────────────────
class ForensicsOrchestrator:

    def run(self):
        Config.OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

        console.print(Panel(
            "[bold cyan]Browser Forensics & Behavioural Profiler[/bold cyan] [dim]v2.0[/dim]\n"
            "[dim]Loading → Extracting → Visualising → Profiling → Evaluating[/dim]",
            border_style="cyan"
        ))

        # ── 1. Load data ─
        console.print(Rule("Step 1 · Loading Data"))
        if not Path(Config.INPUT_JSON).exists():
            console.print(f"[red]❌  File not found:[/red] {Config.INPUT_JSON}")
            console.print("[yellow]ℹ️   Generating synthetic demo data…[/yellow]")
            entries = self._generate_demo_entries()
        else:
            loader  = DataLoader(Config.INPUT_JSON)
            entries = loader.load()

        console.print(f"[green]✓[/green] Loaded [bold]{len(entries)}[/bold] unique entries")

        # ── 2. Extract features ─
        console.print(Rule("Step 2 · Feature Extraction"))
        ext  = FeatureExtractor(entries)
        interests  = ext.extract_interests()
        suspicious = ext.extract_suspicious()
        temporal   = ext.extract_temporal()
        domains    = ext.extract_domains()
        clusters   = ext.cluster_interests()
        risk_level, _ = ext.compute_risk(suspicious)

        date_range = (
            f"{entries[0]['dt'].strftime('%Y-%m-%d')}  →  {entries[-1]['dt'].strftime('%Y-%m-%d')}"
            if entries else "N/A"
        )

        features = {
            "total_entries": len(entries),
            "date_range":    date_range,
            "interests":     interests,
            "suspicious":    suspicious,
            "temporal":      temporal,
            "domains":       domains,
            "clusters":      clusters,
            "risk_level":    risk_level,
        }
        console.print("[green]✓[/green] Features extracted")

        # ── 3. Visualise ─
        console.print(Rule("Step 3 · Visualisation"))
        vis   = Visualiser()
        chart_paths = {
            "heatmap":    vis.hourly_heatmap(entries),
            "domains":    vis.top_domains(domains),
            "interests":  vis.interest_pie(interests),
            "suspicious": vis.suspicious_keywords(suspicious["keyword_hits"]),
        }
        console.print(f"[green]✓[/green] Charts saved → {vis.OUT}")

        # ── 4. LLM Profile ─
        console.print(Rule("Step 4 · LLM Profiling"))
        profiler     = LLMProfiler()
        profile_text = profiler.generate_profile(features)

        # ── 5. Terminal report ─
        console.print(Rule("Step 5 · Report"))
        reporter = ReportGenerator()
        reporter.print_terminal_report(features, profile_text, chart_paths)

        # ── 6. HTML export ─
        html_path = reporter.export_html(features, profile_text)
        console.print(f"[green]✓[/green] HTML report → [underline]{html_path}[/underline]")

        # ── 7. Evaluation ─
        console.print(Rule("Step 6 · Evaluation"))
        evaluator = Evaluator()
        pred = {
            "age":       "20-29",
            "interests": [k for k, _ in interests.most_common(3)],
            "location":  "India",
        }
        eval_results = evaluator.evaluate(pred)
        evaluator.print_eval(eval_results)

        console.print(Rule("[bold green]Complete[/bold green]", style="green"))
        return features, profile_text, eval_results

    # ── Demo entry generator ────────────────────
    @staticmethod
    def _generate_demo_entries() -> list[dict]:
        """Creates synthetic entries so the pipeline runs without a real JSON file."""
        import random
        from datetime import timedelta

        base_ts = int(datetime(2024, 1, 1).timestamp() * 1_000_000)
        sample_titles_urls = [
            ("GitHub - tensorflow/tensorflow", "https://github.com/tensorflow/tensorflow"),
            ("Stack Overflow - Python list comprehension", "https://stackoverflow.com/questions/1234"),
            ("YouTube - Deep Learning Tutorial", "https://youtube.com/watch?v=abc"),
            ("Reddit - r/MachineLearning", "https://reddit.com/r/MachineLearning"),
            ("LinkedIn - Job postings ML Engineer", "https://linkedin.com/jobs"),
            ("Kaggle - House Prices Competition", "https://kaggle.com/competitions"),
            ("Netflix - Stranger Things", "https://netflix.com/watch/123"),
            ("Amazon - Buy laptop", "https://amazon.in/laptop"),
            ("how to hack wifi password tutorial", "https://example.com/hack"),
            ("torrent site download cracked software", "https://1337x.to/search"),
            ("dark web access guide", "https://darkwebguide.com"),
            ("GeeksforGeeks - Binary Search Tree", "https://geeksforgeeks.org/bst"),
            ("Spotify - Playlist Chill vibes", "https://open.spotify.com/playlist/123"),
            ("Coursera - Machine Learning by Andrew Ng", "https://coursera.org/learn/ml"),
            ("NDTV - India News Today", "https://ndtv.com"),
        ]
        entries = []
        for i in range(800):
            title, url = random.choice(sample_titles_urls)
            offset = random.randint(0, 90 * 24 * 3600 * 1_000_000)
            ts = base_ts + offset
            dt = datetime.fromtimestamp(ts / 1_000_000)
            entries.append({
                "title":  title,
                "url":    url,
                "ts":     ts,
                "dt":     dt,
                "hour":   dt.hour,
                "dow":    dt.weekday(),
                "domain": re.search(r"https?://(?:www\.)?([^/?\s]+)", url).group(1),
                "date":   dt.date(),
            })
        entries.sort(key=lambda x: x["ts"])
        return entries


# ─────────────────────────────────────────────
# ENTRY POINT
# ─────────────────────────────────────────────
if __name__ == "__main__":
    orchestrator = ForensicsOrchestrator()
    orchestrator.run()

import random
from datetime import datetime, timedelta

normal = [
    "youtube music", "netflix show", "amazon shopping",
    "github repo", "instagram reels", "reddit memes",
    "linkedin jobs", "stack overflow help"
]

lines = []
for i in range(300):
    t = datetime.now() - timedelta(minutes=random.randint(0, 5000))
    lines.append(f"{t.strftime('%Y-%m-%d %H:%M:%S')}: {random.choice(normal)}")

with open("low_risk.txt", "w") as f:
    f.write("\n".join(lines))

import random
from datetime import datetime, timedelta

normal = ["youtube", "netflix", "amazon", "instagram", "github"]
suspicious = ["torrent download", "phishing tutorial", "dark web info"]

lines = []
for i in range(300):
    t = datetime.now() - timedelta(minutes=random.randint(0, 5000))

    if random.random() < 0.3:
        activity = random.choice(suspicious)
    else:
        activity = random.choice(normal)

    lines.append(f"{t.strftime('%Y-%m-%d %H:%M:%S')}: {activity}")

with open("medium_risk.txt", "w") as f:
    f.write("\n".join(lines))

import random
from datetime import datetime, timedelta

suspicious = [
    "hack wifi password",
    "dark web marketplace",
    "phishing attack tutorial",
    "torrent movies download",
    "malware github code",
    "kali linux hacking tools"
]

lines = []
for i in range(300):
    t = datetime.now() - timedelta(minutes=random.randint(0, 5000))
    activity = random.choice(suspicious)
    lines.append(f"{t.strftime('%Y-%m-%d %H:%M:%S')}: {activity}")

with open("high_risk.txt", "w") as f:
    f.write("\n".join(lines))

import json

input_file = "high_risk.txt"   # your current file
output_file = "Historyy.json"

entries = []

with open(input_file, "r") as f:
    lines = f.readlines()

for line in lines:
    line = line.strip()
    if not line:
        continue

    parts = line.split(": ", 1)
    if len(parts) == 2:
        timestamp = parts[0]
        title = parts[1]

        entries.append({
            "title": title,
            "timestamp": timestamp
        })

# Final JSON structure
data = {
    "Browser History": entries
}

# Save JSON
with open(output_file, "w") as f:
    json.dump(data, f, indent=4)

print("✅ Converted to JSON successfully!")